title: "Dokus Theme"
theme: "hugo-cidb-dokus"
baseURL: https://ci-db.github.io/dokus-site/

outputs:
  home:
    - HTML
    - RSS
    - JSON


cascade:
  - _target:
      path: "**/doc/**"
    type: doc
    layout: single
  - _target:
      path: "**/v/*/**"
    type: doc
    layout: single



  - _target:
      path: "**/v/*"
    type: versions
    layout: list




