title: "Dokus Theme"
theme: "hugo-cidb-dokus"
baseURL: https://ci-db.github.io/dokus-site/

outputs:
  section: [HTML, RSS, print]   
  page: [HTML, print]   
  home:
    - HTML
    - RSS
    - JSON
    - print
    #- HTMLPDF


outputFormats:
  print:
    baseName: index
    isHTML: true
    mediaType: text/html
    path: _print
    permalinkable: false

 


cascade:
  - _target:
      path: "**/doc/**"
    type: doc
    layout: single
  - _target:
      path: "**/v/*/**"
    type: doc
    layout: single



  - _target:
      path: "**/v/*"
    type: versions
    layout: list




