version: "3.9"
services:  
  hugo-solo:
    container_name: "hugo-solo"
    image: monachus/hugo
    volumes:
      - ".:/usr/share/blog"
    ports:
      - "1313:1313"
    #command: hugo -b http://localhost:9080/ --config config.toml,themes/hugo-cidb-dokus/config/config.toml --watch
    command: hugo serve --bind 0.0.0.0 --config config.yaml,themes/hugo-cidb-dokus/config.yaml 
    #command: ./run.sh
    user: "1000"
#  web:
#      image: nginx:latest
#      ports:
#          - "9080:9080"
#      volumes:
#          - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
#          - ./public:/app
#  php:
#      image: php:fpm
#      volumes:
#          - ./public:/app